[package]
name = "spanned_json_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
nom_locate = "4.2.0"
serde = "1.0.190"

[dev-dependencies]
serde_json = "1.0"
